name: lab_movil_2222
description: A new Flutter project.

publish_to: 'none' 

version: 2.15.0+14

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase
  # install other firebase dependencies using https://firebase.flutter.dev/
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.1.1
  cloud_functions: ^3.0.3
  cloud_firestore: ^2.5.2
  firebase_storage: ^10.0.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  url_launcher: ^6.0.8
  video_player: ^2.2.5
  just_audio: ^0.8.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_markdown: ^0.6.2
  file_picker: ^4.0.0
  rxdart: ^0.27.1
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  lints: ^1.0.1

# icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app-icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/backgrounds/
    - assets/gamification/
    - assets/gifs/
    - assets/images/
    - assets/images/chat/
    - assets/backgrounds/decorations/
    - assets/backgrounds/background-decorations/
    - assets/videos/
    - assets/navbar/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Korolev
      fonts:
        - asset: assets/fonts/Korolev-Medium.otf
          weight: 500
        - asset: assets/fonts/Korolev-Light.otf
          weight: 300
        - asset: assets/fonts/Korolev-Bold.otf
          weight: 700
    - family: GothamNarrow
      fonts:
        - asset: assets/fonts/Gotham-Narrow-Book.otf