import 'package:flutter/material.dart';

//Achivo que contiene los themes y fontstyles
//Font Korolev
final korolevFont = TextTheme(
  headline1: TextStyle(
      fontFamily: 'Korolev',
      fontSize: 96,
      color: Colors.white,
      fontWeight: FontWeight.w300),
  headline2: TextStyle(
      fontFamily: 'Korolev',
      fontSize: 60,
      color: Colors.white,
      fontWeight: FontWeight.w300),
  headline3: TextStyle(
      fontFamily: 'Korolev',
      fontSize: 48,
      color: Colors.white,
      fontWeight: FontWeight.w500),
  headline4: TextStyle(
      fontFamily: 'Korolev',
      fontSize: 34,
      color: Colors.white,
      fontWeight: FontWeight.w500),
  headline5: TextStyle(
      fontFamily: 'Korolev',
      fontSize: 24,
      color: Colors.white,
      fontWeight: FontWeight.w500),
  headline6: TextStyle(
      fontFamily: 'Korolev',
      fontSize: 20,
      color: Colors.white,
      fontWeight: FontWeight.w700),
  subtitle1: TextStyle(
      fontFamily: 'Korolev',
      fontSize: 16,
      color: Colors.white,
      fontWeight: FontWeight.w500),
  subtitle2: TextStyle(
      fontFamily: 'Korolev',
      fontSize: 14,
      color: Colors.white,
      fontWeight: FontWeight.w700),
  bodyText1: TextStyle(
      fontFamily: 'Korolev',
      fontSize: 16,
      color: Colors.white,
      fontWeight: FontWeight.w500),
  bodyText2: TextStyle(
      fontFamily: 'Korolev',
      fontSize: 14,
      color: Colors.white,
      fontWeight: FontWeight.w500),
);
